name: "Changelog on PR"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Generate Changelog"
        id: gen_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: "configs/changelog-config.json"
          token: ${{ secrets.PAT }}

      - name: Post Changelog to PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Posting comment to PR #$PR_NUMBER"
          gh pr comment $PR_NUMBER --body "${{ steps.gen_changelog.outputs.changelog }}"