name: "Changelog on PR"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 📋 Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1

      - name: Post Changelog to PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Posting comment to PR #$PR_NUMBER"
          gh pr comment $PR_NUMBER --body "${{ steps.changes.outputs.changes }}"