name: Build and Publish VSIX

on:
  push:
    tags:
      - "v*" # Runs when you push a tag like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build VSIX package
        run: npm run package

      - name: Find the VSIX file
        id: find-vsix
        run: echo "VSIX_FILE=$(ls *.vsix | head -n 1)" >> $GITHUB_ENV

      - name: Get commits since last release
        id: commits
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last tag: $LAST_TAG"
          COMMITS=$(git log $LAST_TAG..HEAD --pretty=format:"- [%h]($REPO_URL/commit/%H) %s (%an)" --no-merges)
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "Commits: $COMMITS"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.VSIX_FILE }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release of version ${{ github.ref_name }}

            ${{ env.COMMITS }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
